### ISSUE TITLE
Two label f1 score makes a systematic error for mulilabel predictions!

### ISSUE THREAD

**Issue by Kruemel23** [KISMED-TUDa/18-ha-2010-pj#2]
We just discovered that your score.py script does not make very much sense for multilabel models. The problem is that the f1 score for two labels is not defined if multiple are predicted: Suppose the model predicts "O" but the true label is "A". Is that a false positive or a false negative? Well We'd say it doesn't make sense. In your script this is just ignored which can lead to extreme high f1 scores for bad models!

**Comment by TixXx1337** [comment]
Changing line 56 onwards to:
        if gt_class == "N" and pred_class in "AO~":
            FP = FP + 1
        if gt_class == "A" and pred_class in "NO~":
            FN = FN + 1

kind of fixes the problem. But then you actually do not calculate the F1 Score!

**Comment by hogius** [comment]
Thanks for pointing this out: As discussed today: For the binary classification evaluation only, we will treat all model outputs other than AFib as normal, i.e. "O" -> "N", "~"-> "N".
